# Copyright (c) 2021 Ecosoft Co., Ltd.

site_name: Your Project Name
copyright: Copyright &copy; 2021 Ecosoft Co., Ltd.
repo_url: https://github.com/ecosoft-odoo/eco_mkdocs  # Add edit on github link
edit_uri: edit/main/docs
theme: readthedocs
nav:  # Content organization
    - Home: index.md
    - Overview: overview.md
    - Some More Topics:
        - Topic 1: some_topic/topic1.md
markdown_extensions:
    - toc:
        permalink: "#"
    - admonition   # Make internal links for hearders H1, H2, etc.
plugins:
    - search
    - with-pdf:  # More params -> https://pypi.org/project/mkdocs-with-pdf/
        cover_title: My Project Documentation
        cover_subtitle: Odoo ERP V14 for Some Company
        cover_logo: ecosoft.png
        author: Kitti U. <kittiu@ecosoft.co.th>

